changes according to the code reviewer
Rifat8080/mahadi_capstone_project_1 pull request #12
Opened 2023-05-23 08:17 UTC by Rifat8080

- Added all request changes according to the previous reviewer
- Added live demo link
- Fixed all margins and paddings

2023-05-23 09:05 UTC, 1GORDON requested changes
##
## Hi @Rifat8080  ✋

Good job so far!

## Highlights!
- Followed GitHub Flow ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

## I would recommend you maintain the same pull request until it is approved to help code reviewers perform quality reviews.

# Status: Required Changes ♻️⛔️

- [ ] As given in the project guidelines kindly ensure your design is a replica of the provided design. You may align the elements of your pages correctly so as to replicate the design given.
- Your design
![your desktop-1](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/43ef3fbb-6021-4cfa-8a3b-bb5dde489677)
![your-desktop-2](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/4abc712d-9c48-4d9e-b697-92c52900e5d4)
- Given design
![Given desktop](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/903c3d03-de8f-4c3f-97ad-cded91409c20)

- [ ] Kindly ensure your programs section has five cards instead of three so that your design can be an imitation of the design given

- Your design
![your programs](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/e518e200-215d-48f0-a38b-335da37b37aa)
- Given design
![Given programs](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/38497ab9-0938-4f10-8736-5fa291f16146)

- [ ] Kindly remove this button from the desktop view. It only exists on the mobile view of the home section.
- Your design
![your desktop button](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/bcb18c34-895b-44d8-a215-9f7705d61f06)

- Given design
![given desktop button](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/7cc96204-7349-4904-9a07-12f7aa0ae335)

- [ ] Kindly ensure the footer section of your about is a replica of the design given.
- Your design
![Your-about section footer](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/96a9621b-1a9b-49da-8f08-f17d334d38bb)
- Given design
![given about footer](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/63917725/c5ea7292-dcd5-40db-b727-26c829531758)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 04:45 UTC, Shedrack-Sunday requested changes
Hello @Rifat8080        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Good job heeding most of the recommendations of the last reviewer  👍 

  
# Required Changes  🌵 

- [x] You made some impressive implementations which I must say is a job well done. However, there are a few  features you missed or need to implement

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-24 04:45 UTC, Shedrack-Sunday commented on about.css
> +}
- [ ] As suggested by the last reviewer, kindly add two more cards to have the same number as specified in the design given.
-The idea is to have you replicate the same design. Kindly add the remaining cards 👍 
- [Optional] The color of the cards is not the same as yours. To have a better design and have a replica that fits perfectly, kindly consider adding the right color which is grey, and The hover on the cards which the last reviewer missed 👍 

## Your work:
![image](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/50990925/e58703d1-2514-45bf-b15b-875a9e8c7c87)

## Design:
![image](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/50990925/16d64320-24ad-48ae-a20a-6701b662191b)

2023-05-24 07:48 UTC, Ibizugbe approved these changes
Hi @Rifat8080 👋👋👋

![VeryNiceNiceGIF (2)](https://github.com/Rifat8080/mahadi_capstone_project_1/assets/64643995/62665fa6-f68f-41f0-915c-d17dfd7419fa)
, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅

- [x] linters are passing👍.
- [x] The appropriate number of cards have been added as requested by the previous reviewer👍.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 07:56 UTC, merged